AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for creating multiple RDS instances'

Parameters:
  Subnet1:
    Default: 'subnet-0b031d4f4ee7454ba'
    Type: String
  Subnet2:
    Default: 'subnet-014f11cd6afcfb70b'
    Type: String
  MyVPCSecurityGroup:
    Default: 'sg-00dcfcc75404a88e5'
    Type: String
  DBSubnetGroup:
    Default: 'test-db-9-dbsubnetgroup-tcvtswpzkwoo'
    Type: String

Resources:
  DBInstance4:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: 'mydbinstance4'
      DBInstanceClass: 'db.t3.micro'
      Engine: 'postgres'
      EngineVersion: '13.10'
      MasterUsername: 'masteruser'
      MasterUserPassword: 'mypassword'
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref MyVPCSecurityGroup
      AllocatedStorage: 5
      MultiAZ: false
      PubliclyAccessible: true
      StorageType: gp2
      StorageEncrypted: false
      EnableIAMDatabaseAuthentication: false
      EnablePerformanceInsights: false
      DeletionProtection: false

